# Generated by Django 2.0.5 on 2018-05-31 15:19

from django.db import migrations, models
import django.db.models.deletion
import jianli.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dir', models.CharField(max_length=100)),
                ('avatar_dir', models.CharField(max_length=100)),
                ('one_sentence_introduction', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=10)),
                ('honors', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duty', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('git_link', models.CharField(max_length=100)),
                ('blog_link', models.CharField(max_length=100)),
                ('full_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StringListField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', jianli.fields.ListField()),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='edu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianli.Edu'),
        ),
        migrations.AddField(
            model_name='cv',
            name='project_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianli.PE'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianli.Skill'),
        ),
    ]
