# Generated by Django 2.0.5 on 2018-06-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu',
            name='id',
        ),
        migrations.AddField(
            model_name='edu',
            name='e_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pe',
            name='p_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='s_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
