# Generated by Django 2.0.5 on 2018-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0003_auto_20180601_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='id',
        ),
        migrations.AddField(
            model_name='cv',
            name='c_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
